#!/usr/bin/env php
<?php

use Faker\Factory;

require __DIR__.'/vendor/autoload.php';

const MAX_USERS = 500;

function formatUsername(string $usr): string
{
	return str_replace('.', '', $usr);
}

function formatPassword(string $pwd): string
{
	return password_hash($pwd, PASSWORD_DEFAULT);
}

echo 'TRUNCATE `user`;'.PHP_EOL;
echo 'INSERT INTO `user` VALUES'.PHP_EOL;
for ($i = 1; $i < MAX_USERS; ++$i) {
	$generator = Factory::create();

	$now = (new DateTime('now'))->format('Y-m-d H:i:s');

	$user = [
		'first' => $generator->firstName,
		'last' => $generator->lastName,
		'usr' => formatUsername($generator->username),
		'mail' => $generator->email,
		'pwd' => formatPassword($generator->password),
		'birth' => ($generator->dateTimeBetween('-60 years', '-18 years'))->format('Y-m-d H:i:s'),
		'gender' => rand(1, 2),
		'orientation' => rand(1, 3),
		'bio' => $generator->paragraph,
		'country' => $generator->country,
		'state' => '',
		'city' => $generator->city,
		'zip' => $generator->postcode,
		'file3' => '',
		'file4' => '',
		'file5' => '',
		'score' => rand(0, 100),
		'token' => md5(microtime(false)),
		'tdate' => $now,
		'active' => rand(0, 1),
		'created' => $now,
		'update' => $now,
	];

	$user['file1'] = $user['gender'] === 1
		? '../0433ff3c68897ea4.jpg'
		: '../3587660-5489214.jpg';

	$user['file2'] = $user['gender'] === 1
		? '../942f1737abf20b24.jpg'
		: '../25479221584697.jpg';

	$user['register'] = $user['active'] === 1
		? rand(0, 1)
		: 0;

	echo sprintf(
		'(%d,"%s","%s","%s","%s","%s","%s",%d,%d,"%s","%s","%s","%s","%s","%s","%s","%s","%s","%s",%d,"%s","%s",%d,%d,"%s","%s"),%s',
		$i,
		$user['first'],
		$user['last'],
		$user['usr'],
		$user['mail'],
		$user['pwd'],
		$user['birth'],
		$user['gender'],
		$user['orientation'],
		$user['bio'],
		$user['country'],
		$user['state'],
		$user['city'],
		$user['zip'],
		$user['file1'],
		$user['file2'],
		$user['file3'],
		$user['file4'],
		$user['file5'],
		$user['score'],
		$user['token'],
		$user['tdate'],
		$user['active'],
		$user['register'],
		$user['created'],
		$user['update'],
		PHP_EOL
	);
}

$generator = Factory::create();

$now = (new DateTime('now'))->format('Y-m-d H:i:s');

$user = [
	'first' => $generator->firstName,
	'last' => $generator->lastName,
	'usr' => formatUsername($generator->username),
	'mail' => $generator->email,
	'pwd' => formatPassword($generator->password),
	'birth' => ($generator->dateTimeBetween('-60 years', '-18 years'))->format('Y-m-d H:i:s'),
	'gender' => rand(1, 2),
	'orientation' => rand(1, 3),
	'bio' => $generator->paragraph,
	'country' => $generator->country,
	'state' => '',
	'city' => $generator->city,
	'zip' => $generator->postcode,
	'file3' => '',
	'file4' => '',
	'file5' => '',
	'score' => rand(0, 100),
	'token' => md5(microtime(false)),
	'tdate' => $now,
	'active' => rand(0, 1),
	'created' => $now,
	'update' => $now,
];

$user['file1'] = $user['gender'] === 1
	? '../0433ff3c68897ea4.jpg'
	: '../3587660-5489214.jpg';

$user['file2'] = $user['gender'] === 1
	? '../942f1737abf20b24.jpg'
	: '../25479221584697.jpg';

$user['register'] = $user['active'] === 1
	? rand(0, 1)
	: 0;

echo sprintf(
	'(%d,"%s","%s","%s","%s","%s","%s",%d,%d,"%s","%s","%s","%s","%s","%s","%s","%s","%s","%s",%d,"%s","%s",%d,%d,"%s","%s");%s',
	$i,
	$user['first'],
	$user['last'],
	$user['usr'],
	$user['mail'],
	$user['pwd'],
	$user['birth'],
	$user['gender'],
	$user['orientation'],
	$user['bio'],
	$user['country'],
	$user['state'],
	$user['city'],
	$user['zip'],
	$user['file1'],
	$user['file2'],
	$user['file3'],
	$user['file4'],
	$user['file5'],
	$user['score'],
	$user['token'],
	$user['tdate'],
	$user['active'],
	$user['register'],
	$user['created'],
	$user['update'],
	PHP_EOL
);
